In [1]:
from __future__ import print_function
import torch
import numpy as np

In [2]:
# construct 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[4.0957e-14, 1.3563e-19, 1.8578e-01],
        [2.0105e+20, 1.2427e+22, 2.7565e-09],
        [1.3556e-19, 7.2053e+22, 4.7428e+30],
        [2.5062e-12, 1.4585e-19, 2.3308e-09],
        [1.1819e+22, 7.0976e+22, 4.7429e+30]])


In [3]:
# construct a randomly initiazlied matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.3520, 0.8377, 0.4024],
        [0.0528, 0.3143, 0.2419],
        [0.3169, 0.7757, 0.9993],
        [0.4479, 0.1354, 0.5075],
        [0.8734, 0.5655, 0.2943]])


In [4]:
# construct a matrix filled with 0
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# construct a tensor directly from data
xx = torch.tensor([5.5, 3], dtype=torch.double)
print(xx)

tensor([5.5000, 3.0000], dtype=torch.float64)


In [6]:
# create a tensor based on an existing tensor
y = xx.new_ones(5, 3)      # new_* methods take in sizes
print('info y:\n', y, '\ndatatype is:', y.dtype)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print('info x:\n', x, x.size())                                      # result has the same size


info y:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) 
datatype is: torch.float64
info x:
 tensor([[ 1.8923,  0.1709, -0.3623],
        [ 0.0096,  0.2679,  0.8625],
        [-0.4323,  0.2025, -0.7003],
        [-0.3118, -0.3441,  0.1338],
        [ 0.4921, -0.4440,  1.5618]]) torch.Size([5, 3])


In [7]:
# or create a tensor without inheriting history tensors.
y = torch.ones(5,3)
print(y, '\ndatatype is:', y.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 
datatype is: torch.float32


**Introduction to Tensor Operations**

In [8]:
# addition 1
y = torch.rand(5, 3)
x = torch.rand_like(y, dtype=torch.float)
print(x + y)
# addition 2
print(torch.add(x, y))

# addtion: providing output tensor as an argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result == (x+y))

# addtion: inplace (內存直接修改)
# adds x to y
y.add_(x)
print(y)

tensor([[0.9142, 0.7049, 0.2709],
        [1.4319, 1.0744, 1.3698],
        [1.2601, 0.4727, 1.3686],
        [0.8324, 1.3013, 0.9930],
        [0.8916, 1.5698, 0.2664]])
tensor([[0.9142, 0.7049, 0.2709],
        [1.4319, 1.0744, 1.3698],
        [1.2601, 0.4727, 1.3686],
        [0.8324, 1.3013, 0.9930],
        [0.8916, 1.5698, 0.2664]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)
tensor([[0.9142, 0.7049, 0.2709],
        [1.4319, 1.0744, 1.3698],
        [1.2601, 0.4727, 1.3686],
        [0.8324, 1.3013, 0.9930],
        [0.8916, 1.5698, 0.2664]])


In [9]:
# std numpy-like operation
print(x[:, 1])

tensor([0.1569, 0.9878, 0.3664, 0.3386, 0.6356])


In [10]:
# resize
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
# 如果是 one-element tensor 可用item()方法取值則不再是torch.tensor, 不同於 x[0].
x= torch.randn(1)
print(x)
print(x[0])
print(x[0].numpy())
print(x.item())

tensor([1.3966])
tensor(1.3966)
1.3966311
1.396631121635437


**NumPy Bridge**

In [5]:
# converting torch tensor to a numpy
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print("ids:(%s,%s); and IS operation: %s" % (id(a), id(b), a is b ))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
ids:(2649284341120,2649283931232); and IS operation: False


In [6]:
# 如果a改變的話會影響b嗎?
a.add_(1)
print(a)
print(b)
print('''The Torch Tensor and NumPy array will share their underlying 
      memory locations, and changing one will change the other.''')
a+=1 #效果同上
print(a)
print(b)

a = a+1 ##此時你把a assign到新的地方並存值=a+1，所以和b斷了聯繫。
print(a)
print(b)

b = a.numpy()
b+=1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
The Torch Tensor and NumPy array will share their underlying 
      memory locations, and changing one will change the other.
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]
tensor([4., 4., 4., 4., 4.])
[3. 3. 3. 3. 3.]
tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


**Converting NumPy Array to Torch Tensor**

In [14]:
# from_numpy()
a = np.ones(5)
b = torch.from_numpy(a)
print(a,'\n',b)

np.add(a, 1, out=a)
print(a, '\n', b)

a += 1
print(a, '\n', b)

b += 1
print(a, '\n', b)

[1. 1. 1. 1. 1.] 
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] 
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] 
 tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] 
 tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


In [7]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    print(device)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

cuda


c:\users\rreal\appdata\local\programs\python\python36\lib\site-packages\torch\cuda\__init__.py:117: UserWarning: 
    Found GPU0 GeForce GT 720M which is of cuda capability 2.1.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))


RuntimeError: cuda runtime error (8) : invalid device function at c:\a\w\1\s\windows\pytorch\aten\src\thc\generic/THCTensorMath.cu:14